### ISSUE TITLE
ошибка в ./api_test_verification_photo.sh

### ISSUE THREAD

**Issue by pi-null-mezon** [EBSBIO/Vendors#1]
Скрипт ./api_test_verification_photo.sh не находит значение "status" в ответе БП на запрос GET /health
![image](https://user-images.githubusercontent.com/5991537/175273530-9d7b70b2-90ea-4e05-b09e-0b76f81b7684.png)

**Comment by Shubarin** [comment]
> Скрипт ./api_test_verification_photo.sh не находит значение "status" в ответе БП на запрос GET /health ![image](https://user-images.githubusercontent.com/5991537/175273530-9d7b70b2-90ea-4e05-b09e-0b76f81b7684.png)

Поддерживаю вопрос. Аналогичная ситуация.

**Comment by kflirik** [comment]
curl -s -w "%{http_code}" --output response_body '$VENDOR_URL
Файл response_body пришлите , пожалуйста.

**Comment by pi-null-mezon** [comment]
git не разрешает файлы без расширения прикладывать сюда, поэтому я вашем запросе добавил расширение .txt
[response_body.txt](https://github.com/EBSBIO/Vendors/files/9011075/response_body.txt)

**Comment by pi-null-mezon** [comment]
чекнул как будет отрабатывать, если убрать кириллицу, чтобы body стало таким:
```
{"message":"","status":0}
```
тот же результат теста - ОШИБКА

**Comment by kflirik** [comment]
Очень странно.
```
#!/bin/bash
REGEXP="\"?[Ss]tatus\"?:\s?0"
# https://github.com/EBSBIO/Vendors/blob/7aef800e931afacb0d6fd8e474494f38d77dc96f/api_test_verification_photo.sh#L213

MESSAGE=$(grep --binary-files=text -e '{.*}' response_body.txt)
# https://github.com/EBSBIO/Vendors/blob/7aef800e931afacb0d6fd8e474494f38d77dc96f/include/f_checks.sh#L45
echo -en "MESSAGE:\n$MESSAGE\n\n"

if [[ $MESSAGE  =~ $REGEXP ]]; then
    echo "OK"
else
    echo "FAIL ($REGEXP is expected)"
fi
```
У меня работает.
Пришлите контейнер, попробую на живом

**Comment by kflirik** [comment]
Запуститте тест с опцией -vv, покажите вывод

**Comment by kflirik** [comment]
Я понял. Вы не создали директорию tmp, в каталоге со скриптами, в которую curl пишет "--output response_body"
Допишу скрипты, чтоб проверял

**Comment by pi-null-mezon** [comment]
почему не добавить её автомтическое создание при необходимости в скриптах?

**Comment by kflirik** [comment]
https://github.com/EBSBIO/Vendors/blob/1d4ad292aa864ad1c5a98739ba6b57a17a855adc/api_test_verification_photo.sh#L216
