### ISSUE TITLE
Reference to not existed file in `samples`

### ISSUE THREAD

**Issue by pi-null-mezon** [EBSBIO/Vendors#20]
I have found that `api_test_liveness.sh` fails for one specific test case because resource file is not existed. To fix this, go to this [line of sources](https://github.com/EBSBIO/Vendors/blob/c1df8244b64af1e1e2d149addde8cc762c98f1e5/include/f_test_passive_liveness_photo.sh#L24) and remove .mp4 in the end of line

HOW IT LOOKS NOW:
```
    VERTICAL_SAMPLE_MP4="resources/samples/vert_passive_video.mp4"
```

HOW IT SHOULD BE:
```
    VERTICAL_SAMPLE_MP4="resources/samples/vert_passive_video"
```

**Comment by Ksyun2142** [comment]
Fixed!
